# Generated by Django 4.1.5 on 2023-01-11 08:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('main_image', models.ImageField(upload_to='blog_images')),
                ('introduction', ckeditor.fields.RichTextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('conclusion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.series')),
                ('tag', models.ManyToManyField(to='App.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
