# Generated by Django 4.1.5 on 2023-01-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_project_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_category',
            name='project',
            field=models.ManyToManyField(blank=True, to='App.project'),
        ),
    ]
