# Generated by Django 4.1.5 on 2023-01-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_project_category_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created']},
        ),
    ]
