# Generated by Django 4.1.5 on 2023-01-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_blog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
