# Generated by Django 4.1.5 on 2023-01-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_series_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
